name: CI/CD PIPELINE FOR DEVOPS

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Test build image
        run: docker compose build

  deploy:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: SSH and Deploy to AWS EC2
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd ~/task-manager-devops
            docker compose pull
            docker compose up -d
            docker image prune -f
